---
version: '3.8'

services:
  centos7:
    container_name: 'centos7'
    build:
      context: ./
      dockerfile: Dockerfile
    image: centos7:development
    command: 'tail -f /dev/null'
    working_dir: '/root/'
    volumes:
      - ./src/:/root
